apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-gitops-routes-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: gitops_routess_alerts
    interval: 1m
    rules:
    - alert: GitOpsRoutesHealthErrors
      expr: |
        (
          sum(openshift_route_status{ status="True", namespace="gitops-service-argocd"})
          by (source_cluster)
        )
        /
        (
          sum(openshift_route_status{namespace="gitops-service-argocd"})
          by (source_cluster)
        ) < 0.95
      for: 5m
      labels:
        severity: warning
        slo: true
      annotations:
        summary: >-
          Less than 95% of GitOps Routes are in Healthy state: {{ $value | humanizePercentage }}
        description: >-
          The percentage total of Argo CD Routes that are in Healthy state is less than 95%.
        runbook_url: https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/gitops/routes.md
